// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF7kL3NMJuusvoehvDiEmO1IuYqb7ivKs',
    appId: '1:265228302970:web:b80d95d6773816424699c3',
    messagingSenderId: '265228302970',
    projectId: 'keylol-app',
    authDomain: 'keylol-app.firebaseapp.com',
    storageBucket: 'keylol-app.appspot.com',
    measurementId: 'G-4EVNXQFZMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_-ZbZzS4bG50qbmeLf3YEWqWvXEfZ1aI',
    appId: '1:265228302970:android:32e79747f7d001a94699c3',
    messagingSenderId: '265228302970',
    projectId: 'keylol-app',
    storageBucket: 'keylol-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2dHT7e3wgEBLPqmD0gN8625jn17UfVEs',
    appId: '1:265228302970:ios:48679501d133481d4699c3',
    messagingSenderId: '265228302970',
    projectId: 'keylol-app',
    storageBucket: 'keylol-app.appspot.com',
    iosClientId: '265228302970-0hbni52vh1c5tueci166dnbt1kqh3m6t.apps.googleusercontent.com',
    iosBundleId: 'com.cdgeass.keylolFlutter',
  );
}
