# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '17'
    
      # Setup flutter environment
      - uses: subosito/flutter-action@v1
          
      - name: Update all submodules
        run: git submodule update --recursive --remote --init

      - name: Build
        run: |
          flutter pub get
          flutter build apk --no-tree-shake-icons

      # Nightly Release
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: "KeylolF Nightly Release"
          prerelease: true
          files: |
            ./build/app/outputs/flutter-apk/app-release.apk
